### PR TITLE
Development

### PR DESCRIPTION
**Pull request by caravagn**

### CODE REVIEW

**Comment by luca-dex** [comment]
You last commits fixed some of the error we had. Now I find this one:
```
--- re-building 'a2_plotting.Rmd' using rmarkdown

Quitting from lines 98-106 (a2_plotting.Rmd) 

##[error]Error: processing vignette 'a2_plotting.Rmd' failed with diagnostics:

Can't subset columns that don't exist.

x Columns `Tail`, `C1`, and `C2` don't exist.

--- failed re-building 'a2_plotting.Rmd'
```

**Comment by luca-dex** [comment]
The problems seems to be in the object you're passing to `plot_latent_variables(best_fit, cutoff_assignment = 0)`

```
> print(best_fit)
-- [ MOBSTER ] My MOBSTER model n = 5000 with k = 2 Beta(s) and a tail ---------
* Clusters: p = 55% [C1], 31% [Tail], and 14% [C2], with p > 0.
* Tail [n = 1370, 31%] with alpha = 1.2.
* Beta C1 [n = 2784, 55%] with mean = 0.48.
* Beta C2 [n = 846, 14%] with mean = 0.15.
i Score(s): NLL = -5671.5; ICL = -10359.09 (-11266.35), H = 907.26 (0). Fit
converged by MM in 75 steps.
i The fit object model contains also drivers annotated.
# A tibble: 3 x 7
     VAF cluster   Tail       C1       C2 is_driver driver_label
   <dbl> <chr>    <dbl>    <dbl>    <dbl> <lgl>     <chr>
1 0.448  C1      0.0125 9.88e- 1 8.08e-21 TRUE      DR1
2 0.159  C2      0.225  2.35e-34 7.75e- 1 TRUE      DR2
3 0.0629 Tail    1.00   1.91e-82 4.02e- 5 TRUE      DR3
```

This is the object used in the example of the function `plot_latent_variables`

```
> print(fit_example$best)
-- [ MOBSTER ] My MOBSTER model n = 5000 with k = 2 Beta(s) and a tail ---------
* Clusters: p = 55% [C1], 31% [Tail], and 14% [C2], with p > 0.
* Tail [n = 1370, 31%] with alpha = 1.2.
* Beta C1 [n = 2784, 55%] with mean = 0.48.
* Beta C2 [n = 846, 14%] with mean = 0.15.
i Score(s): NLL = -5671.5; ICL = -10359.09 (-11266.35), H = 907.26 (0). Fit
converged by MM in 75 steps.
```

Here the differences:

```
> a = best_fit
> b = fit_example$best
> all.equal(a, b)
[1] "Component \"data\": Length mismatch: comparison on first 2 components"
[2] "Component \"Call\": target, current do not match when deparsed"
> a$d
a$data        a$description
> a$data
# A tibble: 5,000 x 7
     VAF cluster    Tail    C1       C2 is_driver driver_label
   <dbl> <chr>     <dbl> <dbl>    <dbl> <lgl>     <chr>
 1 0.497 C1      0.00736 0.993 5.22e-27 FALSE     <NA>
 2 0.490 C1      0.00669 0.993 4.42e-26 FALSE     <NA>
 3 0.470 C1      0.00705 0.993 1.31e-23 FALSE     <NA>
 4 0.517 C1      0.0130  0.987 1.83e-29 FALSE     <NA>
 5 0.506 C1      0.00903 0.991 3.86e-28 FALSE     <NA>
 6 0.440 C1      0.0179  0.982 9.68e-20 FALSE     <NA>
 7 0.428 C1      0.0347  0.965 3.88e-18 FALSE     <NA>
 8 0.523 C1      0.0164  0.984 3.97e-30 FALSE     <NA>
 9 0.482 C1      0.00648 0.994 3.87e-25 FALSE     <NA>
10 0.499 C1      0.00759 0.992 3.20e-27 FALSE     <NA>
# ... with 4,990 more rows
> b$data
# A tibble: 5,000 x 2
     VAF cluster
   <dbl> <chr>
 1 0.497 C1
 2 0.490 C1
 3 0.470 C1
 4 0.517 C1
 5 0.506 C1
 6 0.440 C1
 7 0.428 C1
 8 0.523 C1
 9 0.482 C1
10 0.499 C1
# ... with 4,990 more rows
>
```

Same thing for the dimension of the `Call` attribute

**Comment by luca-dex** [comment]
First issue seems to be solved, now we have:

```
Quitting from lines 79-89 (a6_CloneTrees.Rmd) 
##[error]Error: processing vignette 'a6_CloneTrees.Rmd' failed with diagnostics:
'plot.ctree' is not an exported object from 'namespace:ctree'
--- failed re-building ‘a6_CloneTrees.Rmd’
```

**Comment by caravagn** [comment]
Hey was this solved with yesterday's upgrade of `ctree`?

**Comment by luca-dex** [comment]
Let's check...

**Comment by luca-dex** [comment]
That one is ok, now we have:

```
── Running fits ─────────────────────────────────── Might take some time ...  ──
Quitting from lines 60-67 (a3_bootstrap.Rmd) 
Error: processing vignette 'a3_bootstrap.Rmd' failed with diagnostics:
5 simultaneous processes spawned
--- failed re-building ‘a3_bootstrap.Rmd’
```

and 

```
> ### Name: bootstrapped_statistics
> ### Title: Compute boostrap statistics from a bootstrap run.
> ### Aliases: bootstrapped_statistics
> 
> ### ** Examples
> 
> # Random small dataset
> dataset = random_dataset(N = 200, seed = 123, Beta_variance_scaling = 100)
> x = mobster_fit(dataset$data, auto_setup = 'FAST')
 [ MOBSTER fit ] 

Error in mobster:::check_input(x, K, samples, init, tail, epsilon, maxIter,  : 
  There are some reserved names in the input data that cannot be used, please remove or rename columns: cluster
Calls: mobster_fit -> <Anonymous>
Execution halted
```

**Review by luca-dex — APPROVED** [review]

**Comment by luca-dex** [comment]
I'm solving the issue of simultaneous processes spawned.

For the second one the problem is basically the following.

With the `random_dataset`function, the `data` contains a tibble in this form:

```
> random_dataset(100)
$data
# A tibble: 99 x 2
     VAF cluster
   <dbl> <chr>  
 1 0.893 C1     
 2 0.872 C1     
 3 0.886 C1     
 4 0.921 C1     
 5 0.904 C1     
 6 0.869 C1     
 7 0.895 C1     
 8 0.860 C1     
 9 0.900 C1     
10 0.868 C1     
# … with 89 more rows
[ ... ]
```

When this dataset is processed as shown in the example of the `bootstrapped_statistics`, there is a check executed by the `check_input` function which block the executio. `cluster` seems to be a reserver internal keyword in mobster:

```R
# Check input column names, something should be reserved
  fixed_names = c("cluster", "Tail", paste0("C", 1:100))
  fixed_names = fixed_names[which(fixed_names %in% colnames(x))]
  
  if(length(fixed_names) > 0){
    stop("There are some reserved names in the input data that cannot be used, please remove or rename columns: ", paste0(fixed_names, collapse = ', '))
  }
```

**Pull request merged**
